pipeline {
    agent {
        docker { 
            label 'docker-host'  
            image 'maven:3.8.6-jdk-8'  
        }
    }

      environment {
        GITHUB_CREDENTIALS = credentials('github-secret-as-username-password')
        AEM_AUTHOR_PORT = "4502"
        AEM_PUBLISH_PORT = "4503"
    }
    stages {
        stage('Code Checkout') {
            steps{
                checkout scm
            }
        }
        
        stage('Build Stage') {
            stages {
                stage("AEM Build"){
                    when { changeset "seekerstore/**" }
                   
                    steps {
                        script{
                            withCredentials([
                                usernamePassword(credentialsId: 'aem-creds', passwordVariable: 'AEM_PASSWORD', usernameVariable: 'AEM_USER'),
                                string(credentialsId: 'aem-author-publish-host', variable: 'AEM_HOST')
                                ]) {
                                
                                sh "cd seekerstore && mvn clean install -PautoInstallPackageAuthorPublish -DBuildVersion=${BUILD_NUMBER} -DAemHost=${AEM_HOST} -DAemUser=${AEM_USER} -DAemPassword=${AEM_PASSWORD} -DAemAuthorPort=${AEM_AUTHOR_PORT} -DAemPublishPort=${AEM_PUBLISH_PORT}"
                                
                            }
                        }
                    }
                    post {
                        always {
                            emailext to: "aravindarali125@gmail.com",
                            subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}"
                        }
                    }
                }
               

                }   
            }
        }
    
    post {
        failure {
            emailext to: "aravindarali125@gmail.com",
            subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
            recipientProviders: [[$class: 'DevelopersRecipientProvider']]
        }
    }
}